
language:
  - swift
osx_image: xcode10.1
before_install:
  - pod repo update
script:
  - xcodebuild -scheme MarvelApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
cache:
  directories:
    - $HOME/.cocoapods/
